// Generated by Haxe 4.3.1
#ifndef INCLUDED_HLSL
#define INCLUDED_HLSL

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(HLSL)



class HXCPP_CLASS_ATTRIBUTES HLSL_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef HLSL_obj OBJ_;
		HLSL_obj();

	public:
		enum { _hx_ClassId = 0x042446c1 };

		void __construct(::String inFile,::String inProfile,::String inVariable,::String inTarget);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="HLSL")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"HLSL"); }
		static ::hx::ObjectPtr< HLSL_obj > __new(::String inFile,::String inProfile,::String inVariable,::String inTarget);
		static ::hx::ObjectPtr< HLSL_obj > __alloc(::hx::Ctx *_hx_ctx,::String inFile,::String inProfile,::String inVariable,::String inTarget);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~HLSL_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("HLSL",9d,50,d1,2f); }

		::String file;
		::String profile;
		::String target;
		::String variable;
		void build();
		::Dynamic build_dyn();

};


#endif /* INCLUDED_HLSL */ 
