// Generated by Haxe 4.3.1
#ifndef INCLUDED_Linker
#define INCLUDED_Linker

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(Compiler)
HX_DECLARE_CLASS0(Linker)
HX_DECLARE_CLASS0(Target)



class HXCPP_CLASS_ATTRIBUTES Linker_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Linker_obj OBJ_;
		Linker_obj();

	public:
		enum { _hx_ClassId = 0x4f1e228f };

		void __construct(::String inExe);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="Linker")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"Linker"); }
		static ::hx::ObjectPtr< Linker_obj > __new(::String inExe);
		static ::hx::ObjectPtr< Linker_obj > __alloc(::hx::Ctx *_hx_ctx,::String inExe);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Linker_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Linker",07,57,39,21); }

		::String mExe;
		::Array< ::String > mFlags;
		::String mOutFlag;
		::String mExt;
		::String mNamePrefix;
		::String mLibDir;
		::String mRanLib;
		::String mFromFile;
		bool mFromFileNeedsQuotes;
		::Array< ::String > mLibs;
		bool mExpandArchives;
		bool mRecreate;
		::String mLastOutName;
		::String mAddLibPath;
		bool isOutOfDate(::String inName,::Array< ::String > inObjs);
		::Dynamic isOutOfDate_dyn();

		::String getSimpleFilename( ::Target inTarget);
		::Dynamic getSimpleFilename_dyn();

		::String getUnstrippedFilename(::String inObjDir, ::Target inTarget);
		::Dynamic getUnstrippedFilename_dyn();

		::String link( ::Target inTarget,::Array< ::String > inObjs, ::Compiler inCompiler,::Array< ::String > extraDeps);
		::Dynamic link_dyn();

};


#endif /* INCLUDED_Linker */ 
