name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Windows-Build:
    runs-on: windows-latest
    steps:  
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2
          
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp 4.3.2
          set MINGW_ROOT=C:/mingw64
        shell: cmd
      - name: Version Tag
        run: echo "${{github.run_id}}" > VERSION
        
      - name: Compile CPPIA
        run: |
          cd project
          haxe compile-cppia.hxml -D HXCPP_MINGW
          cd ../

      - name: Compile Tools
        run: |
          cd tools/hxcpp
          haxe compile-cpp.hxml -D HXCPP_MINGW
          cd ../../

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: Windows-Build
          path: bin/Windows64

  Build-Download: 
    name: Build-Download
    runs-on: windows-latest
    needs: Windows-Build
    steps:
    - name: Download Artifact 
      uses: actions/download-artifact@main
      with: 
        name: Windows-Build
